name: mind

include:
  - docker-compose-worlds.yaml
  - docker-compose-agents.yaml

services:
  mindserver:
    build:
      context: mindserver
    ports:
      - "8080:8080"
    environment:
      MINDSERVER_PORT: 8080
      OPENAI_API_KEY:
      NODE_ENV: production
    networks:
      - mind_network
    depends_on:
      - redis
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./mindserver/src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync
          path: ./mindserver/public
          target: /app/public
        - action: rebuild
          path: mindserver/package.json
  registry:
    image: registry:2.7
    ports:
      - "5000:5000"
    networks:
      - mind_network
  fastapi:
    build:
      context: fastapi
    ports:
      - "8008:80"
    environment:
      OPENAI_API_KEY:
    command: ["fastapi", "run", "main.py", "--port", "80", "--reload"]
    networks:
      - mind_network
    depends_on:
      redis:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: fastapi/main.py
          target: /app/main.py
  redis:
    image: redis/redis-stack:latest  # This includes Redis + RedisSearch
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight web UI
    networks:
      - mind_network
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  mind_network:
    driver: bridge
