name: mind

include:
  - docker-compose-worlds.yaml
  - docker-compose-agents.yaml

services:
  tasks:
    build:
      context: tasks
    ports:
      - "3000-3003:3000-3003" # see the view from the camera mounted on your bot head: http://localhost:3000/
      - "8000:8000"
    environment:
      LOGFIRE_TOKEN:
      OPENAI_API_KEY:
  react:
    build:
      context: react
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY:
    networks:
      - mind_network
    develop:
      watch:
        - action: sync
          path: react
          target: /app
  elysia:
    build:
      context: elysia
    ports:
      - "3002:80"
    environment:
      OPENAI_API_KEY:
    networks:
      - mind_network
    depends_on:
      - redis
    command: ["bun", "dev"]
    develop:
      watch:
        - action: sync
          path: elysia
          target: /app
  mindserver:
    build:
      context: mindserver
    ports:
      - "8080:8080"
    environment:
      MINDSERVER_PORT: 8080
#      OPENAI_API_KEY:
    networks:
      - mind_network
#    depends_on:
#      - redis
#    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./mindserver/src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync
          path: ./mindserver/public
          target: /app/public
        - action: rebuild
          path: mindserver/package.json
  registry:
    image: registry:2.7
    ports:
      - "5000:5000"
    networks:
      - mind_network
  fastapi:
    build:
      context: fastapi
    ports:
      - "8008:80"
    environment:
      OPENAI_API_KEY:
      LOGFIRE_TOKEN:
    command: ["fastapi", "run", "main.py", "--port", "80", "--reload"]
    networks:
      - mind_network
    depends_on:
      redis:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: fastapi/main.py
          target: /app/main.py
  redis:
    image: redis/redis-stack:latest  # This includes Redis + RedisSearch
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight web UI
    networks:
      - mind_network
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  mind_network:
    driver: bridge
