x-common:
  server-config: &common-server-config
    tty: true
    stdin_open: true
    build: &common-world-building
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"

services:
  flat:
    <<: *common-server-config
    build:
      <<: *common-world-building
      target: world-flat
    image: pi2.local:5000/worlds/flat
    ports:
      - "25565:25565"
  easy:
    <<: *common-server-config
    build:
      <<: *common-world-building
      target: world-easy
    image: pi2.local:5000/worlds/easy
    ports:
      - "25566:25565"
