x-common:
  agent-env: &agent-env
    MINECRAFT_HOST: "pi2.local"
    MINECRAFT_PORT: "25565"
    INSECURE_CODING: "true"
  agent: &agent
    networks:
      - mind_network
    build:
      context: agent
      platforms:
        - "linux/amd64"
#        - "linux/arm64"

services:
  andy:
    <<: *agent
    environment:
      <<: *agent-env
  gpt:
    extends:
      service: andy
    environment:
      PROFILE: gpt
  claude:
    extends:
      service: andy
    environment:
      ANTHROPIC_API_KEY:
      PROFILE: claude
  gemini:
    extends:
      service: andy
    environment:
      GEMINI_API_KEY:
      PROFILE: gemini