name: mind

x-common:
  environment: &env
    VERSION: "1.20.4"
    EULA: "TRUE"
    MEMORY: "2048M"
    SEED: "-183412789913619791"
    MAX_PLAYERS: "2"
    ONLINE_MODE: "false"
    USE_AIKAR_FLAGS: "true"
    TZ: "America/New_York"
    SERVER_PORT: 55916
    OPS: |-
      davidseibert

services:
  ai:
    build:
      context: .
    environment:
      MINECRAFT_HOST: flat
      MINECRAFT_PORT: 25565
      BOT_VIEWS: true
      INSECURE_CODING: true
#      VISION: true
      OPENAI_API_KEY:
    ports:
      - "3000:3000" # see the view from the camera mounted on your bot head: http://localhost:3000/
      - "8080:8080"
  easy:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25566:55916"
    environment:
      <<: *env
      MODE: "0"
      DIFFICULTY: "1"
      LEVEL: "easy world"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "false"
      SPAWN_NPCS: "true"
      FORCE_GAME_MODE: "true"
    volumes:
      - easy:/data
  flat:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      <<: *env
      SERVER_PORT: 25565
      MODE: "1"
      DIFFICULTY: "1"
      LEVEL: "flat world"
      LEVEL_TYPE: "flat"
      ALLOW_FLIGHT: "true"
      ENABLE_COMMAND_BLOCK: "true"
      SPAWN_ANIMALS: "false"
      SPAWN_MONSTERS: "false"
      SPAWN_NPCS: "true"
      FORCE_GAME_MODE: "true"
    volumes:
      - flat:/data

volumes:
  flat:
  easy:
