name: mind

x-common:
  server-config: &common-server-config
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
  server-env: &common-server-env
    VERSION: "1.20.4"
    EULA: "TRUE"
    MEMORY: "2048M"
    SEED: "993690229419782480"
    MAX_PLAYERS: "4"
    ONLINE_MODE: "false"
    USE_AIKAR_FLAGS: "true"
    TZ: "America/New_York"
    SERVER_PORT: 25565
    FORCE_GAME_MODE: "false"
  keys: &keys
    OPENAI_API_KEY:
    ANTHROPIC_API_KEY:
    GEMINI_API_KEY:


services:
  andy:
    build:
      context: .
    environment:
      OPENAI_API_KEY:
      MINECRAFT_HOST: "flat"
      MINECRAFT_PORT: "25565"
      INSECURE_CODING: "true"
    depends_on:
      flat:
        condition: service_healthy
  gpt:
    extends:
      service: andy
    environment:
      PROFILE: gpt
  claude:
    extends:
      service: andy
    environment:
      ANTHROPIC_API_KEY:
      PROFILE: claude
  gemini:
    extends:
      service: andy
    environment:
      GEMINI_API_KEY:
      PROFILE: gemini
  easy:
    <<: *common-server-config
    ports:
      - "25566:25565"
    environment:
      <<: *common-server-env
      MODE: "0"
      DIFFICULTY: "1"
      LEVEL: "easy world"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "false"
      SPAWN_NPCS: "true"
    volumes:
      - easy:/data
  flat:
    <<: *common-server-config
    ports:
      - "25565:25565"
    environment:
      <<: *common-server-env
      SERVER_PORT: 25565
      MODE: "1"
      DIFFICULTY: "1"
      LEVEL: "flat world"
      LEVEL_TYPE: "flat"
      ALLOW_FLIGHT: "true"
      ENABLE_COMMAND_BLOCK: "true"
      SPAWN_ANIMALS: "false"
      SPAWN_MONSTERS: "false"
      SPAWN_NPCS: "true"
    volumes:
      - flat:/data

volumes:
  flat:
  easy:
